services:
  db:
    image: postgres
    container_name: chat_rg
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    volumes:
      - chat_rg_main_db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis:6.2-alpine
    container_name: duck-chat-cache
    volumes:
      - cache-data:/var/lib/redis/data
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

volumes:
  chat_rg_main_db-data:
  cache-data:
